apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: koding
spec:
  type: NodePort
  ports:
  - name: "api-port"
    port: 27017
    protocol: ""
    targetPort: 27017
  selector:
    service: mongo
