apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: koding
spec:
  type: NodePort
  ports:
  - name: ""
    port: 6379
    protocol: ""
    targetPort: 6379
  selector:
    service: redis
