apiVersion: v1
kind: Service
metadata:
  name: countly
  namespace: koding
spec:
  type: NodePort
  ports:
  - name: "api-port"
    port: 32768
    protocol: ""
    targetPort: 32768
  selector:
    service: countly
