apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    service: countly
  name: countly
  namespace: koding
spec:
  replicas: 1
  selector:
    service: countly
  template:
    metadata:
      labels:
        service: countly
        app: countly-ext-service
    spec:
      containers:
        - name: countly
          image: koding/countly-server:latest
          ports:
            - containerPort: 32768
          workingDir: /opt/koding
