apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    service: postgres
  name: postgres
  namespace: koding
spec:
  replicas: 1
  selector:
    service: postgres
  template:
    metadata:
      labels:
        service: postgres
        app: postgres-ext-service
    spec:
      containers:
        - name: postgres
          image: koding/postgres:latest
          ports:
            - containerPort: 5432
              hostPort: 5432
          workingDir: /opt/koding
