apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: koding
spec:
  type: NodePort
  ports:
  - name: ""
    port: 5432
    protocol: ""
    targetPort: 5432
  selector:
    service: postgres
