apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: koding
spec:
  type: NodePort
  ports:
  - name: "service-port"
    port: 5672
    protocol: ""
    targetPort: 5672
  - name: "api-port"
    port: 15672
    protocol: ""
    targetPort: 15672
  selector:
    service: rabbitmq
